# Project: Project8
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test1-4.o
LINKOBJ  = test1-4.o
LIBS     = -L"D:/Train/DevCppPortable/MinGW64/lib" -L"D:/Train/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Train/DevCppPortable/MinGW64/include" -I"D:/Train/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/Train/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Train/DevCppPortable/MinGW64/include" -I"D:/Train/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/Train/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Train/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = test1-4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

test1-4.o: test1-4.c
	$(CC) -c test1-4.c -o test1-4.o $(CFLAGS)
