# Project: Class9
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 1095.o
LINKOBJ  = 1095.o
LIBS     = -L"D:/train/cpp/DevCppPortable/MinGW64/lib" -L"D:/train/cpp/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/train/cpp/DevCppPortable/MinGW64/include" -I"D:/train/cpp/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/train/cpp/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/train/cpp/DevCppPortable/MinGW64/include" -I"D:/train/cpp/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/train/cpp/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/train/cpp/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Class9.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

1095.o: 1095.cpp
	$(CPP) -c 1095.cpp -o 1095.o $(CXXFLAGS)
